/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    teams: Team;
    drivers: Driver;
    races: Race;
    predictions: Prediction;
    'race-ratings': RaceRating;
    'season-stats': SeasonStat;
    events: Event;
    'event-responses': EventResponse;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    drivers: DriversSelect<false> | DriversSelect<true>;
    races: RacesSelect<false> | RacesSelect<true>;
    predictions: PredictionsSelect<false> | PredictionsSelect<true>;
    'race-ratings': RaceRatingsSelect<false> | RaceRatingsSelect<true>;
    'season-stats': SeasonStatsSelect<false> | SeasonStatsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-responses': EventResponsesSelect<false> | EventResponsesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'broadcast-settings': BroadcastSetting;
  };
  globalsSelect: {
    'broadcast-settings': BroadcastSettingsSelect<false> | BroadcastSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Уникальное отображаемое имя (3-20 символов)
   */
  nickname: string;
  /**
   * Например: @username (опционально)
   */
  telegramUsername?: string | null;
  /**
   * HEX цвет для отображения в таблице лидеров и графиках
   */
  chartColor: string;
  /**
   * Виртуальная валюта для покупок в магазине
   */
  pitCoins?: number | null;
  name?: string | null;
  roles?: ('admin' | 'user')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: string;
  /**
   * Например: Red Bull Racing, Mercedes-AMG Petronas
   */
  name: string;
  logo?: (string | null) | Media;
  /**
   * Например: #0600EF для Red Bull
   */
  teamColor: string;
  /**
   * Снимите галочку, чтобы скрыть команду из списка для прогнозов
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivers".
 */
export interface Driver {
  id: string;
  name: string;
  shortName: string;
  number?: number | null;
  photo?: (string | null) | Media;
  /**
   * Выберите команду-конструктор из справочника
   */
  team?: (string | null) | Team;
  /**
   * Флаг страны рождения пилота
   */
  countryFlag?: (string | null) | Media;
  /**
   * Год сезона (например, 2025)
   */
  season: number;
  /**
   * Снимите галочку, чтобы скрыть пилота из списка для прогнозов
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "races".
 */
export interface Race {
  id: string;
  /**
   * Например: Monaco Grand Prix
   */
  name: string;
  /**
   * Год сезона (например, 2026)
   */
  season: number;
  round: number;
  /**
   * Рекомендуемый размер: 500x500px
   */
  countryFlag: string | Media;
  /**
   * Только значение атрибута d тега <path>. Без обёртки <svg>. viewBox: 144 144 512 512
   */
  trackSVGPath?: string | null;
  predictionOpenDate: string;
  /**
   * Обычно за несколько часов до начала гонки
   */
  predictionCloseDate: string;
  raceDate: string;
  /**
   * Обновляется автоматически при голосовании пользователей
   */
  rating?: {
    ratingBad?: number | null;
    ratingNormal?: number | null;
    ratingGood?: number | null;
  };
  /**
   * Заполняется после завершения гонки для расчета баллов
   */
  results?:
    | {
        position: number;
        driver: string | Driver;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "predictions".
 */
export interface Prediction {
  id: string;
  user: string | User;
  race: string | Race;
  predictions: {
    position: number;
    driver: string | Driver;
    id?: string | null;
  }[];
  /**
   * Рассчитывается автоматически после ввода результатов гонки
   */
  points?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-ratings".
 */
export interface RaceRating {
  id: string;
  user: string | User;
  race: string | Race;
  rating: 'bad' | 'normal' | 'good';
  updatedAt: string;
  createdAt: string;
}
/**
 * Кешированная статистика пользователей по сезонам
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "season-stats".
 */
export interface SeasonStat {
  id: string;
  user: string | User;
  /**
   * Год сезона (например, 2025)
   */
  season: number;
  /**
   * Сумма всех очков за прогнозы на гонки
   */
  totalPoints: number;
  /**
   * Очки за прогноз победителей сезона (макс. 140)
   */
  seasonPredictionPoints: number;
  /**
   * totalPoints + seasonPredictionPoints
   */
  totalPointsWithSeasonPrediction: number;
  predictionsCount: number;
  /**
   * Количество прогнозов где все 3 позиции угаданы точно
   */
  perfectPredictions: number;
  /**
   * Количество гонок подряд с прогнозами
   */
  currentStreak: number;
  /**
   * Максимальный стрик за сезон
   */
  bestStreak: number;
  /**
   * Данные для графиков эволюции очков
   */
  raceHistory?:
    | {
        race: string | Race;
        points: number;
        /**
         * Сумма очков с начала сезона до этой гонки включительно
         */
        cumulativePoints: number;
        /**
         * Место пользователя в этой гонке (опционально)
         */
        rank?: number | null;
        id?: string | null;
      }[]
    | null;
  lastCalculated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Универсальные события: голосования, квизы, предсказания
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * general: обычные голосования и квизы | season-prediction: прогноз итогов сезона
   */
  eventType: 'general' | 'season-prediction';
  /**
   * Краткое название (например: "Голосование за MVP сезона")
   */
  name: string;
  /**
   * Подробное описание события для пользователей
   */
  description?: string | null;
  /**
   * draft: не виден пользователям | open: принимаются ответы | closed: ответы закрыты | completed: результаты подведены
   */
  status: 'draft' | 'open' | 'closed' | 'completed';
  /**
   * Тип награды для всех вопросов в этом событии
   */
  rewardType: 'points' | 'pit-coins';
  /**
   * Добавьте один или несколько вопросов
   */
  questions: {
    questionText: string;
    questionType: 'single-choice' | 'multiple-choice' | 'yes-no' | 'driver-select' | 'team-select';
    /**
     * Количество очков/монет за правильный ответ на этот вопрос
     */
    rewardPoints: number;
    /**
     * Добавьте варианты для single-choice и multiple-choice
     */
    options?:
      | {
          optionText: string;
          /**
           * Отметьте правильные варианты (устанавливается после закрытия)
           */
          isCorrect?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Правильный ответ для вопроса типа Да/Нет
     */
    correctAnswer?: ('yes' | 'no') | null;
    /**
     * Выберите правильного пилота после завершения события
     */
    correctDriver?: (string | null) | Driver;
    /**
     * Выберите правильную команду после завершения события
     */
    correctTeam?: (string | null) | Team;
    id?: string | null;
  }[];
  /**
   * Опционально: привязка к сезону Ф1
   */
  season?: number | null;
  openedAt?: string | null;
  closedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ответы пользователей на события
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-responses".
 */
export interface EventResponse {
  id: string;
  user: string | User;
  event: string | Event;
  /**
   * Ответы пользователя на каждый вопрос
   */
  answers: {
    /**
     * Порядковый номер вопроса в массиве questions события
     */
    questionIndex: number;
    selectedOptions?:
      | {
          optionIndex: number;
          id?: string | null;
        }[]
      | null;
    /**
     * Значение: "yes" или "no"
     */
    selectedAnswer?: string | null;
    /**
     * ID выбранного пилота
     */
    selectedDriver?: (string | null) | Driver;
    /**
     * ID выбранной команды
     */
    selectedTeam?: (string | null) | Team;
    id?: string | null;
  }[];
  /**
   * Рассчитывается автоматически после завершения события
   */
  correctAnswersCount?: number | null;
  /**
   * Очки или Pit Coins (в зависимости от типа награды события)
   */
  reward?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'teams';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'drivers';
        value: string | Driver;
      } | null)
    | ({
        relationTo: 'races';
        value: string | Race;
      } | null)
    | ({
        relationTo: 'predictions';
        value: string | Prediction;
      } | null)
    | ({
        relationTo: 'race-ratings';
        value: string | RaceRating;
      } | null)
    | ({
        relationTo: 'season-stats';
        value: string | SeasonStat;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'event-responses';
        value: string | EventResponse;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nickname?: T;
  telegramUsername?: T;
  chartColor?: T;
  pitCoins?: T;
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  teamColor?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivers_select".
 */
export interface DriversSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  number?: T;
  photo?: T;
  team?: T;
  countryFlag?: T;
  season?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "races_select".
 */
export interface RacesSelect<T extends boolean = true> {
  name?: T;
  season?: T;
  round?: T;
  countryFlag?: T;
  trackSVGPath?: T;
  predictionOpenDate?: T;
  predictionCloseDate?: T;
  raceDate?: T;
  rating?:
    | T
    | {
        ratingBad?: T;
        ratingNormal?: T;
        ratingGood?: T;
      };
  results?:
    | T
    | {
        position?: T;
        driver?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "predictions_select".
 */
export interface PredictionsSelect<T extends boolean = true> {
  user?: T;
  race?: T;
  predictions?:
    | T
    | {
        position?: T;
        driver?: T;
        id?: T;
      };
  points?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-ratings_select".
 */
export interface RaceRatingsSelect<T extends boolean = true> {
  user?: T;
  race?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "season-stats_select".
 */
export interface SeasonStatsSelect<T extends boolean = true> {
  user?: T;
  season?: T;
  totalPoints?: T;
  seasonPredictionPoints?: T;
  totalPointsWithSeasonPrediction?: T;
  predictionsCount?: T;
  perfectPredictions?: T;
  currentStreak?: T;
  bestStreak?: T;
  raceHistory?:
    | T
    | {
        race?: T;
        points?: T;
        cumulativePoints?: T;
        rank?: T;
        id?: T;
      };
  lastCalculated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  eventType?: T;
  name?: T;
  description?: T;
  status?: T;
  rewardType?: T;
  questions?:
    | T
    | {
        questionText?: T;
        questionType?: T;
        rewardPoints?: T;
        options?:
          | T
          | {
              optionText?: T;
              isCorrect?: T;
              id?: T;
            };
        correctAnswer?: T;
        correctDriver?: T;
        correctTeam?: T;
        id?: T;
      };
  season?: T;
  openedAt?: T;
  closedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-responses_select".
 */
export interface EventResponsesSelect<T extends boolean = true> {
  user?: T;
  event?: T;
  answers?:
    | T
    | {
        questionIndex?: T;
        selectedOptions?:
          | T
          | {
              optionIndex?: T;
              id?: T;
            };
        selectedAnswer?: T;
        selectedDriver?: T;
        selectedTeam?: T;
        id?: T;
      };
  correctAnswersCount?: T;
  reward?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broadcast-settings".
 */
export interface BroadcastSetting {
  id: string;
  isLive?: boolean | null;
  /**
   * Имя Twitch канала, например: limonov_f1
   */
  twitchChannel?: string | null;
  /**
   * Имя VK канала, например: f1_live
   */
  vkChannel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broadcast-settings_select".
 */
export interface BroadcastSettingsSelect<T extends boolean = true> {
  isLive?: T;
  twitchChannel?: T;
  vkChannel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}